language: node_js
node_js:
  - '6'
  - '7'

before_script:
  - npm install -g bit-bin

before_install:
  - node --version


addons:
  apt:
    packages:
      - git

branches:
  only:
  - master

cache:
  directories:
  - node_modules
  - lib
  - lib-legacy

os:
  - linux
