language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'

before_install:
  - sudo npm install bit-bin
  - node --version


addons:
  apt:
    packages:
      - git

branches:
  only:
  - master

cache:
  directories:
  - node_modules
  - lib
  - lib-legacy

os:
  - linux
